//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const aura_39386_128_png = "../assets/aura_39386_128.png";
export const aura_39386_512_png = "../assets/aura_39386_512.png";
export const manifest_json = "../assets/manifest.json";
export const serviceworker_js = "../assets/serviceworker.js";
